<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [ ]:
from error_analysis_funs import *

methods = ['pencil', 'qeep-cons']

#phases = np.sort([4.92450833, 1.79547251])
rng = np.random.RandomState(43)
#phases = rng.uniform(0, 2*np.pi, 4) #[3, 4.1]
#[4.77144,    2.82579877, 4.88021636, 0.41070768, 3.06350016]
phases = [5.24546792, 0.65845334, 4.67871413, 2.26509356]
phases = [4.8222519,  2.94910126, 4.55763116, 1.29759215]
phases = [6.01796812, 1.42388327, 3.04547254, 3.09110619]
phases = [2.97370168, 1.67763323, 4.82127149, 1.2842484 ]
phases = [4.90301101, 0.91312365, 3.78069144, 4.34930837]
phases = [2.16439288, 5.13072126, 0.01004995, 1.45654705]
phases = [3.39579597, 2.19846845, 1.34311512, 4.99612169]
num_phases = len(phases)

final_error = 1e-5
alpha = 2
gamma = 2.4
epsilons = [0.02]

cutoff = 1/ num_phases / 3

amplitudes = np.ones(num_phases)/num_phases

estimates = {}
costs = {}
for method in methods:
    estimates[method] = {}
    costs[method] = {}

for method in methods:
    for eps in epsilons:
        
        print(method, eps)
        e,c, error_flag  = multiorder_estimation(method,
                             phases, amplitudes,
                             eps, alpha, gamma,
                             final_error, cutoff)
        print(error_flag)
        estimates[method][eps] = e
        costs[method][eps] = c

pencil 0.02


/home/teobrien/work/projects/heisenberg_limited_multiphase/Alicja_github/qpe/qeep_estimators.py:54: RuntimeWarning: divide by zero encountered in log
  numpy.log(1 - confidence**(1 / num_points_sampled)) / error**4)))


phase estimates, order 0
[3.78069145 4.34930837 0.91312364 4.903011  ]
expected error: 0.02
entering kappa finder
[3, 21, 7, 17, 3, 14]
trying at order d:  1
aliased phase estimates at order 1
[1.9031609  0.02289157 3.56931047 5.07754223]
expected phase estimates at this order
[4.90301101 0.91312365 3.78069144 4.34930837]
[3.5693105  5.07754222 0.02289159 1.90316093]
expected phase estimates at this order from prev order
[3.78069145 4.34930837 0.91312364 4.903011  ]
[0.02289168 1.90316095 5.07754211 3.56931037]
phase estimates at order 1
[4.34930837 3.78069144 4.90301101 0.91312365]
expected error: 0.001393079166501494
trying at order d:  2
entering kappa finder
input data:
[1.445508872853995, 0.8768919437641626, 1.9992115125871042, 4.292509462613532] 0.02 14.356685880406173
[50, 48, 249, 98, 299, 201]
aliased phase estimates at order 2
[0.95983827 6.19187613 2.74303996 5.21604487]
expected phase estimates at this order
[4.90301101 0.91312365 3.78069144 4.34930837]
[0.95983826 5.216044

/home/teobrien/work/projects/heisenberg_limited_multiphase/Alicja_github/qpe/qeep_estimators.py:54: RuntimeWarning: divide by zero encountered in log
  numpy.log(1 - confidence**(1 / num_points_sampled)) / error**4)))


phase estimates, order 0
[0.91754452 3.76991118 4.34836316 4.90686853]
expected error: 0.02
entering kappa finder
[21, 17, 14, 4, 7, 3]
trying at order d:  1
aliased phase estimates at order 1
[0.05983986 1.91487552 3.53055174 4.90686853]
expected phase estimates at this order
[4.90301101 0.91312365 3.78069144 4.34930837]
[3.54481182 4.91048854 0.06815806 1.91308128]
expected phase estimates at this order from prev order
[0.91754452 3.76991118 4.34836316 4.90686853]
[4.97368279 6.19724474 1.89957002 3.59995317]
phase estimates at order 1
[3.78010953 4.34943389 4.90201342 0.91287041]
expected error: 0.001399137149632019
trying at order d:  2
entering kappa finder
input data:
[0.8832900066922251, 1.4526143711952708, 2.0051939014482265, 4.299236193710499] 0.02 14.294524311115687
[50, 98, 297, 48, 248, 200]
aliased phase estimates at order 2
[0.41887902 3.05183286 3.90953752 5.14622797]
expected phase estimates at this order
[4.90301101 0.91312365 3.78069144 4.34930837]
[5.15748857 3.04941

In [1]:
from sparse_qpe import kappa_finder, check_kappa_works, abs_phase_difference
import numpy as np

phases = np.array([1.4517186975677034, 0.8833266072124437, 4.299071863673749, 2.006089730665623])
prev_multiplier = 18.494044745487873
new_kappa = 404.7180712989534 / prev_multiplier
# for phij in phases:
#     for phil in phases:
#         phasediff = abs_phase_difference(phij, phil)
#         thetadiff = abs_phase_difference(phij * new_kappa * prev_multiplier - phil * new_kappa * prev_multiplier, 0)
#         print (phij, phil, phasediff, thetadiff, abs_phase_difference(prev_multiplier * new_kappa * abs(phij - phil), 0),
#                abs_phase_difference(prev_multiplier * new_kappa * phasediff, 0))

phases = np.array([1.4517186975677034, 0.8833266072124437, 4.299071863673749, 2.006089730665623])
prev_multiplier = 18.494044745487873
new_kappa =  kappa_finder(phases, 0.02, prev_multiplier)
print(new_kappa)
print((phases * prev_multiplier * new_kappa) % (2 * np.pi))
print(4 * 0.02 * (1 + new_kappa))
print(min([abs(phij - phil) for phij in (phases * prev_multiplier * new_kappa) % (2 * np.pi)
           for phil in (phases * prev_multiplier * new_kappa) % (2 * np.pi)
           if phij != phil]))
print(min([(abs(phij - phil) * prev_multiplier * new_kappa) % (2 * np.pi) for phij in phases for phil in phases if phij != phil]))
check_kappa_works(phases, new_kappa, 0.02, prev_multiplier)
cutoff = (np.pi - 2 * 0.02 * (1 + new_kappa)) / (prev_multiplier * new_kappa)

[64, 321, 62, 385, 126, 258]
15.670642629671883
[6.03754227 4.67262168 1.85865641 3.33897027]
1.3336514103737505
1.333651410373676
1.3649205961188642


In [ ]:
plt.figure(figsize = (10, 6))
for i,eps in enumerate(epsilons):
    plt.subplot(1,len(epsilons),i+1)
    for method in methods:
        estimation_errors = [get_estimation_errors(estimates[method][eps][:(d+1)], phases)
                             for d in range(len(estimates[method][eps]))]
        plt.scatter([c for c_vec in costs[method][eps] for c in c_vec],
                    [e for e_vec in estimation_errors for e in e_vec ], label = method)
    plt.yscale('log')
    plt.xscale('log')
    plt.title(f'$\epsilon = {eps}$')
    plt.legend()
plt.show()

In [ ]:
plt.figure(figsize = (16, 12))
i = 0
for eps in epsilons:
    for method in methods:
        i+=1
        plt.subplot(len(epsilons), len(methods), i, projection='polar')
        plot_phase_estimates(phases, estimates[method][eps], np.ceil(np.log2(2*eps/final_error)).astype('int'))
        plt.title(method+f', $\epsilon$ = {eps}')
plt.show()